### ISSUE TITLE
$HOME/.luarocks… on paths

### ISSUE THREAD

**Issue by bjornbm** [oploadk/localua#4] opened 2023-03-20 09:54 UTC
Some directories outside of the localua installation directory (`Users/bjorn/repos/.localua` in my example below) are present in the luarocks paths:

./.localua/bin/luarocks path
export LUA_PATH='/private/tmp/localua-MwI1H6/luarocks-3.9.2/src/?.lua;/Users/bjorn/repos/.localua/share/lua/5.4/?.lua;/Users/bjorn/repos/.localua/share/lua/5.4/?/init.lua;/Users/bjorn/repos/.localua/lib/lua/5.4/?.lua;/Users/bjorn/repos/.localua/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua;**/Users/bjorn/.luarocks/share/lua/5.4/?.lua;/Users/bjorn/.luarocks/share/lua/5.4/?/init.lua'**
export LUA_CPATH='/Users/bjorn/repos/.localua/lib/lua/5.4/?.so;/Users/bjorn/repos/.localua/lib/lua/5.4/loadall.so;./?.so;**/Users/bjorn/.luarocks/lib/lua/5.4/?.so**'

It seems this would compromise the isolation of a localua installation? I haven't investigated where these come from, and in my case `$HOME/.luarocks` does not exist so it is not causing a problem (yet).

**Comment by catwell** [comment] 2023-03-20 10:40
Good point. Currently localua isolates the System part of Luarocks and not the User part. It would make sense, especially since we use `--force-config`. My goal is not to completely sandbox but it should be isolated if the user does not explicitly try to access external modules.

I think this issue and #3 only come from the wrapper scripts which are generated by LuaRocks itself. I will try to fix it when I have a little time.

**Comment by bjornbm** [comment] 2023-03-20 10:46
Sure. As mentioned no urgency on my part as neither issue is causing trouble. My quick digging also seemed to suggest that these paths elements come from the luarocks build process, but I didn't go in depth.

**Comment by catwell** [comment] 2023-03-29 21:33
Just to consign it here: I confirmed the issues comes from the wrapper script generation process during `make boostrap` (`luarocks 
 make`). There is [a special case](https://github.com/luarocks/luarocks/blob/9a3c5a879849f4f411a96cf1bdc0c4c7e26ade42/src/luarocks/fs/unix.lua#L94-L102) which is annoying because `package.path` and `package.cpath` are not just the paths for our isolated Lua here (because then the bootstrap could not run).

I have a few hacky ideas to fix it but I would prefer to figure out a clean one.

**Comment by catwell** [comment] 2023-04-01 09:53
@bjornbm I have made [a PR](https://github.com/oploadk/localua/pull/5) that should fix this and #3. Can you check on your end that it works?

I won't merge it immediately because I would like to check that I am not breaking macOS first (I cannot test easily because I do not have a Mac, I should add basic CI someday...)

**Comment by bjornbm** [comment] 2023-04-01 16:45
Hi @catwell, #3 was fixed but this one was not it seems: 

./.localua/bin/luarocks path
export LUA_PATH='/Users/bjorn/repos/.localua/share/lua/5.4/?.lua;/Users/bjorn/repos/.localua/share/lua/5.4/?/init.lua;/Users/bjorn/repos/.localua/lib/lua/5.4/?.lua;/Users/bjorn/repos/.localua/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua;**/Users/bjorn/.luarocks/share/lua/5.4/?.lua;/Users/bjorn/.luarocks/share/lua/5.4/?/init.lua**'
export LUA_CPATH='/Users/bjorn/repos/.localua/lib/lua/5.4/?.so;/Users/bjorn/repos/.localua/lib/lua/5.4/loadall.so;./?.so;**/Users/bjorn/.luarocks/lib/lua/5.4/?.so**'
export PATH='**/Users/bjorn/.luarocks/bin:**/Users/bjorn/repos/.localua/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:…

Note that PATH also includes $HOME/.luarocks/bin. I had failed to note this in https://github.com/oploadk/localua/issues/4#issue-1631753189.

FYI I am on a mac.

**Comment by catwell** [comment] 2023-04-01 17:32
It's hard to debug without a Mac, afaik it is fixed on Linux and MSYS2. Can you post:

- the output of `.localua/bin/luarocks config` ;
- the contents of the file `.localua/bin/luarocks`.

Also, run `.localua/bin/luarocks config config_files` and post the contents of all configuration files it returns.

Finally, post the output of the script after the line "Cleaning up luarocks isolation..." (I suspect the issue might be my sed command to remove user configuration fails on Mac).

**Comment by bjornbm** [comment] 2023-04-02 10:14
> It's hard to debug without a Mac, afaik it is fixed on Linux and MSYS2.

That's understood.

> Finally, post the output of the script after the line "Cleaning up luarocks isolation..." (I suspect the issue might be my sed command to remove user configuration fails on Mac).

I think you may have hit the the nail on the head. Here is this output (the second line looks like something didn't behave as expected):

```
Cleaning up luarocks isolation...
sed: -I or -i may not be used with stdin

luarocks 3.9.2-1 is now installed in /Users/bjorn/repos/.localua (license: MIT)

/tmp/localua-Gb6qkV ~/repos
~/repos
```

MacOS `sed` probably doesn't behave exactly the same as GNU sed. For example, from the [manpage](https://www.unix.com/man-page/osx/1/sed/):

```
STANDARDS
     The sed utility is expected to be a superset of the IEEE Std 1003.2
     (“POSIX.2”) specification.

     The -E, -I, -a and -i options, the special meaning of -f -, the prefixing “+”
     in the second member of an address range, as well as the “I” flag to the
     address regular expression and substitution command are non-standard FreeBSD
     extensions and may not be available on other operating systems.
```

More specifically, with macOS sed, the `-i` flag takes an extension (see `-I`):

```
     -I extension
             Edit files in-place, saving backups with the specified extension.  If
             a zero-length extension is given, no backup will be saved.  It is not
             recommended to give a zero-length extension when in-place editing
             files, as you risk corruption or partial content in situations where
             disk space is exhausted, etc.

             Note that in-place editing with -I still takes place in a single
             continuous line address space covering all files, although each file
             preserves its individuality instead of forming one output stream.  The
             line counter is never reset between files, address ranges can span
             file boundaries, and the “$” address matches only the last line of the
             last file.  (See Sed Addresses.) That can lead to unexpected results
             in many cases of in-place editing, where using -i is desired.

     -i extension
             Edit files in-place similarly to -I, but treat each file independently
             from other files.  In particular, line numbers in each file start at
             1, the “$” address matches the last line of the current file, and
             address ranges are limited to the current file.  (See Sed Addresses.)
             The net result is as though each file were edited by a separate sed
             instance.
```

So it would seem:

1. Line 111 takes the `"$lr_config_file"` as the extension to use for backups, as opposed to the file to edit in place.
2. Also, macOS `sed` seems to require having the file name(s) at the end of the `sed` command.

So I think maybe line 111 would have to be changed to:

```bash
        sed -i.bkup -e '/name = "user"/d' "$lr_config_file" && rm "$lr_config_file.bkup"
```

I couldn't figure out how to avoid the creation of the backup file (that is, to pass a zero-length extension) in a way that is compatible with both GNU sed and macOS sed. Also not that I have not tested on Linux, so I'm going by the [online manual](https://www.gnu.org/software/sed/manual/sed.html) for GNU sed `-i` behavior.

Testing on my mac, the sed error message above disappears and `$HOME/.luarocks` no longer appears in the paths:

```
bjorn@Narcissus repos % ./.localua/bin/luarocks path
export LUA_PATH='/Users/bjorn/repos/.localua/share/lua/5.4/?.lua;/Users/bjorn/repos/.localua/share/lua/5.4/?/init.lua;/Users/bjorn/repos/.localua/lib/lua/5.4/?.lua;/Users/bjorn/repos/.localua/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua'
export LUA_CPATH='/Users/bjorn/repos/.localua/lib/lua/5.4/?.so;/Users/bjorn/repos/.localua/lib/lua/5.4/loadall.so;./?.so'
export PATH='/Users/bjorn/repos/.localua/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin…
```

--------------------------

Here are the other outputs you requested, in the order requested, in case you still want/need to see them. These were taken _without_ the change above to line 111:

# `./.localua/bin/luarocks config` =>

```lua
accept_unknown_fields = false
arch = "macosx-x86_64"
cache = {
   luajit_version_checked = true
}
cache_fail_timeout = 86400
cache_timeout = 60
check_certificates = false
cmake_generator = "Unix Makefiles"
config_files = {
   nearest = "/Users/bjorn/repos/.localua/etc/luarocks/config-5.4.lua",
   system = {
      file = "/Users/bjorn/repos/.localua/etc/luarocks/config-5.4.lua",
      found = true
   },
   user = {
      file = "/Users/bjorn/.luarocks/config-5.4.lua",
      found = false
   }
}
connection_timeout = 30
deploy_bin_dir = "/Users/bjorn/repos/.localua/bin"
deploy_lib_dir = "/Users/bjorn/repos/.localua/lib/lua/5.4"
deploy_lua_dir = "/Users/bjorn/repos/.localua/share/lua/5.4"
deps_mode = "one"
disabled_servers = {}
export_path_separator = ":"
external_deps_dirs = {
   "/usr/local",
   "/usr",
   "/",
   "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr",
   "/usr/local/opt"
}
external_deps_patterns = {
   bin = {
      "?"
   },
   include = {
      "?.h"
   },
   lib = {
      "/?/lib/lib?.dylib",
      "lib?.tbd",
      "lib?.a",
      "lib?.so",
      "lib?.so.*"
   }
}
external_deps_subdirs = {
   bin = "bin",
   include = "include",
   lib = {
      "",
      "lib"
   }
}
external_lib_extension = "dylib"
fs_use_modules = true
gcc_rpath = false
home = "/Users/bjorn"
home_tree = "/Users/bjorn/.luarocks"
homeconfdir = "/Users/bjorn/.luarocks"
hooks_enabled = true
lib_extension = "so"
lib_modules_path = "/lib/lua/5.4"
link_lua_explicitly = false
local_by_default = false
local_cache = "/Users/bjorn/.cache/luarocks"
lua_extension = "lua"
lua_found = {
   lua_bindir = "/Users/bjorn/repos/.localua/bin",
   lua_dir = "/Users/bjorn/repos/.localua",
   lua_interpreter = "lua",
   lua_version = "5.4"
}
lua_interpreter = "lua"
lua_modules_path = "/share/lua/5.4"
lua_version = "5.4"
no_manifest = false
obj_extension = "o"
processor = "x86_64"
program_version = "3.9.2"
rocks_dir = "/Users/bjorn/repos/.localua/lib/luarocks/rocks-5.4"
rocks_servers = {
   {
      "https://luarocks.org",
      "https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/",
      "https://luafr.org/luarocks/"
   }
}
rocks_subdir = "/lib/luarocks/rocks-5.4"
rocks_trees = {
   {
      name = "user",
      root = "/Users/bjorn/.luarocks"
   },
   {
      name = "system",
      root = "/Users/bjorn/repos/.localua"
   }
}
runtime_external_deps_patterns = {
   bin = {
      "?"
   },
   include = {
      "?.h"
   },
   lib = {
      "/?/lib/lib?.dylib",
      "lib?.tbd",
      "lib?.so",
      "lib?.so.*"
   }
}
runtime_external_deps_subdirs = {
   bin = "bin",
   include = "include",
   lib = {
      "",
      "lib"
   }
}
static_lib_extension = "a"
sysconfdir = "/Users/bjorn/repos/.localua/etc/luarocks"
target_cpu = "x86_64"
upload = {
   api_version = "1",
   server = "https://luarocks.org",
   tool_version = "1.0.0"
}
user_agent = "LuaRocks/3.9.2 macosx-x86_64"
variables = {
   AR = "ar",
   BUNZIP2 = "bunzip2",
   CC = "env MACOSX_DEPLOYMENT_TARGET=11.0 gcc",
   CFLAGS = "-O2 -fPIC",
   CHMOD = "chmod",
   CMAKE = "cmake",
   CP = "cp",
   CURL = "curl",
   CURLNOCERTFLAG = "-k",
   CVS = "cvs",
   FIND = "find",
   GIT = "git",
   GPG = "gpg",
   GUNZIP = "gunzip",
   HG = "hg",
   ICACLS = "icacls",
   LD = "env MACOSX_DEPLOYMENT_TARGET=11.0 gcc",
   LIBFLAG = "-bundle -undefined dynamic_lookup -all_load",
   LIB_EXTENSION = "so",
   LS = "ls",
   LUA = "/Users/bjorn/repos/.localua/bin/lua",
   LUALIB = "liblua.a",
   LUA_BINDIR = "/Users/bjorn/repos/.localua/bin",
   LUA_DIR = "/Users/bjorn/repos/.localua",
   LUA_INCDIR = "/Users/bjorn/repos/.localua/include",
   LUA_LIBDIR = "/Users/bjorn/repos/.localua/lib",
   LUA_LIBDIR_FILE = "liblua.a",
   MAKE = "make",
   MD5 = "md5",
   MD5SUM = "md5sum",
   MKDIR = "mkdir",
   MKTEMP = "mktemp",
   OBJ_EXTENSION = "o",
   OPENSSL = "openssl",
   PWD = "pwd",
   RANLIB = "ranlib",
   RM = "rm",
   RMDIR = "rmdir",
   ROCKS_TREE = "/Users/bjorn/repos/.localua/lib/luarocks/rocks-5.4",
   RSYNC = "rsync",
   RSYNCFLAGS = "--exclude=.git -Oavz",
   SCP = "scp",
   SCRIPTS_DIR = "/Users/bjorn/repos/.localua/bin",
   SEVENZ = "7z",
   SSCM = "sscm",
   SVN = "svn",
   TAR = "tar",
   TEST = "test",
   TOUCH = "touch",
   UNZIP = "unzip -n",
   WGET = "wget",
   WGETNOCERTFLAG = "--no-check-certificate",
   ZIP = "zip"
}
web_browser = "open"
wrapper_suffix = ""
```

# `cat .localua/bin/luarocks` =>

```sh
#!/bin/sh

LUAROCKS_SYSCONFDIR='/Users/bjorn/repos/.localua/etc/luarocks' exec '/Users/bjorn/repos/.localua/bin/lua' -e 'package.path="/Users/bjorn/repos/.localua/share/lua/5.4/?.lua;/Users/bjorn/repos/.localua/share/lua/5.4/?/init.lua;/Users/bjorn/repos/.localua/lib/lua/5.4/?.lua;/Users/bjorn/repos/.localua/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua;/Users/bjorn/.luarocks/share/lua/5.4/?.lua;/Users/bjorn/.luarocks/share/lua/5.4/?/init.lua";package.cpath="/Users/bjorn/repos/.localua/lib/lua/5.4/?.so;/Users/bjorn/repos/.localua/lib/lua/5.4/loadall.so;./?.so;/Users/bjorn/.luarocks/lib/lua/5.4/?.so";local k,l,_=pcall(require,"luarocks.loader") _=k and l.add_context("luarocks","3.9.2-1")' '/Users/bjorn/repos/.localua/lib/luarocks/rocks-5.4/luarocks/3.9.2-1/bin/luarocks' "$@"
```

# `./.localua/bin/luarocks config config_files` =>

```lua
{
   nearest = "/Users/bjorn/repos/.localua/etc/luarocks/config-5.4.lua",
   system = {
      file = "/Users/bjorn/repos/.localua/etc/luarocks/config-5.4.lua",
      found = true
   },
   user = {
      file = "/Users/bjorn/.luarocks/config-5.4.lua",
      found = false
   }
}
```

**Comment by catwell** [comment] 2023-04-02 11:52
Thanks! Yes I think that's why my other uses of sed in the script did not rely on the inplace flag. I will fix it.

**Comment by catwell** [comment] 2023-04-04 09:10
I pushed the sed change to the branch, can you try again?

**Comment by bjornbm** [comment] 2023-04-05 08:15
Seems to be working correctly now!

**Comment by catwell** [comment] 2023-04-08 05:42
I have released it (merged into master and it is now the version downloaded from https://loadk.com). Thanks!

**Closed as completed by catwell** 2023-04-08 05:42 UTC

**Comment by bjornbm** [comment] 2023-04-08 05:52
Great, thank YOU!
